### ISSUE TITLE
error since update

### ISSUE THREAD

**Issue by prodash841** [Waterboy1602/Addarr#107]
Love the work! 

Getting this error since i updated today. it happens when searching for the series or movie, the bot doesnt return anything and this is the error logged. 

No expert but sounds like the info from the arr's is coming back wrong maybe??? 

No error handlers are registered, logging exception.,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update,
    handler.handle_update(update, self, check, context),
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update,
    new_state = handler.handle_update(update, dispatcher, check_result, context),
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update,
    return self.callback(update, context),
  File "/app/addarr.py", line 264, in choiceSerieMovie,
    return searchSerieMovie(update, context),
  File "/app/addarr.py", line 306, in searchSerieMovie,
    searchResult = service.search(title),
  File "/app/radarr.py", line 24, in search,
    parsed_json = json.loads(req.text),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads,
    return _default_decoder.decode(s),
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()),
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode,
    raise JSONDecodeError("Expecting value", s, err.value) from None,
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mcbane1981** [comment]
I habe the exact same problem after the update.

**Comment by Waterboy1602** [comment]
Are you both using the latest version of Radarr (V4)? Otherwise I can't think of a reason why it doesn't work. On my end it still works.

**Comment by mcbane1981** [comment]
Yes, i am using V4  (4.0.4.5922). I am dockerized versions of Radarr, Sonarr and Addarr.

**Comment by anast20sm** [comment]
It is because v4 does no longer support legacy API.
You can modify the code to work by changing line the query builder endpoints, like modifying line 23 of "radarr.py" to 
`req = requests.get(commons.generateApiQuery("radarr", "movie/lookup", parameters))`

**Comment by anast20sm** [comment]
It is because radarr V4 no longer supports the old API. Upgrade Addarr to last version where it is already updated to v3 API

**Comment by anast20sm** [comment]
Same here, changing manually url paths to v3 API worked for me (will try to test and modify the queries that are not working). Seems to be due v4 does no longer support old radarr API.

**Comment by anast20sm** [comment]
I had exactly the same error but updating to current Addarr version solved it @mcbane1981 @prodash841

**Comment by mcbane1981** [comment]
Thank you @anast20sm! Updating to the latest addarr version fixed the error.
