### ISSUE TITLE
Some Series with too much Seasons and Episodes are causing list index out of range

### ISSUE THREAD

**Issue by mac-110** [Waterboy1602/Addarr#114]
I tried to add a tv show  and then I selected from Season 0 in the bot offer in the telegram channel and then I saw this in the logs of Addarr

`No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/app/src/addarr.py", line 703, in addSerieMovie
    added = service.addToLibrary(idnumber, path, qualityProfile, tags, seasonsSelected)
  File "/app/src/sonarr.py", line 64, in addToLibrary
    data = json.dumps(buildData(parsed_json, path, qualityProfileId, tags, seasonsSelected))
  File "/app/src/sonarr.py", line 87, in buildData
    "languageProfileId": getLanguageProfileId(config["languageProfile"]),
  File "/app/src/sonarr.py", line 176, in getLanguageProfileId
    return languageId[0]
IndexError: list index out of range`

**Comment by Waterboy1602** [comment]
If I look at your logs it doesn't look like it has to do with the fact that there could be too many seasons. The logs say something about `config["languageProfile']`. Are you sure you've filled it in correctly in `config.yaml`? With the latest release you can fill in the name of the profile, instead of an id.

**Comment by Waterboy1602** [comment]
Closed after no response for a long time
