### ISSUE TITLE
Path on config.yaml doubt

### ISSUE THREAD

**Issue by facutopa** [Waterboy1602/Addarr#115]
Hi!

First of all thanks for the job and for the new release!
One question, what mean the field "path" on the config.yaml file?
![imagen](https://user-images.githubusercontent.com/7283431/158232447-6497c96b-4252-4de7-8b6a-d20bef62a235.png)
Because I'm getting this error when I tried to add some tvshow or movie:

> 2022-03-14 17:53:58,862 - addarr - DEBUG - User entered a title friends
> 2022-03-14 17:53:58,863 - addarr - DEBUG - user_data[choice] is Series, skipping step of selecting movie/series
> No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
>     handler.handle_update(update, self, check, context)
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
>     new_state = handler.handle_update(update, dispatcher, check_result, context)
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
>     return self.callback(update, context)
>   File "/app/src/addarr.py", line 534, in pathSerieMovie
>     paths = [p for p in paths if p["path"] not in excluded_root_folders]
>   File "/app/src/addarr.py", line 534, in <listcomp>
>     paths = [p for p in paths if p["path"] not in excluded_root_folders]

On telegram show:
![imagen](https://user-images.githubusercontent.com/7283431/158232767-4f486006-1ef8-463a-8968-c19ce91a4c11.png)
But after push "Yes, add this", the message on the log appear and I don't get anything more.
I ask about the path because maybe this is the problem that generate the fail.

Thanks and regards!

**Comment by facutopa** [comment]
Yep, you're right, 
I completed with the new data of config.yaml but without the "-", example of my old config.yaml:

>   excludedRootFolders: 
>   excludedQualityProfiles:
>   defaultTags: 
>   adminRestrictions: false

The correct now:

>   excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
>     - # First excluded folder, add others with a "-" on a new line (same indentation)
>   excludedQualityProfiles:
>     - 
>   defaultTags: # If set must be existing tags
>     - telegram
>   adminRestrictions: false

Dude, I love you, finally work the bot! Thanks a lot!!!
Regards
