### ISSUE TITLE
Bot Won't Accept Certain User Inputs

### ISSUE THREAD

**Issue by spiveym** [Waterboy1602/Addarr#134]
I had an issue today (Sept-27) whereby the bot would not accept/recognise all of the available commands as part of regular user input. When I sent a command to the bot, it only provided responses in the Telegram chat for the following:

Want to see this text again? Use /help.
• To authenticate before first use you should use /auth.
• To check which series are in Sonarr you can use /allSeries.
• To check which movies are in Radarr you can use /allMovies.

If I sent any of the below commands, no response was provided by the bot:

• To add a movie or series use /start. 
• To delete a movie or series use /delete. 
• To immediately add a movie or series you can use /movie or /series. 
• To toggle the up- and download speed of Transmission use /transmission. 
• To change the up- and download speed of Sabnzbd use /sabnzbd.

I have included the logs below, which include errors received on Sept 26. Note that the issue was resolved by me restarting the container (2022-09-27T23:15:11.628123214Z)

> 2022-09-26T01:10:19.635906707Z Error while getting Updates: Bad Gateway
2022-09-26T01:10:19.670436152Z No error handlers are registered, logging exception.
2022-09-26T01:10:19.670536151Z Traceback (most recent call last):
2022-09-26T01:10:19.670561910Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
2022-09-26T01:10:19.670587039Z     if not action_cb():
2022-09-26T01:10:19.670610372Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
2022-09-26T01:10:19.670634650Z     updates = self.bot.get_updates(
2022-09-26T01:10:19.670657649Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 226, in get_updates
2022-09-26T01:10:19.670681001Z     updates = super().get_updates(
2022-09-26T01:10:19.670703760Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
2022-09-26T01:10:19.670727500Z     result = func(*args, **kwargs)
2022-09-26T01:10:19.670750982Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 3057, in get_updates
2022-09-26T01:10:19.670774426Z     self._post(
2022-09-26T01:10:19.670797648Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
2022-09-26T01:10:19.670821444Z     return self.request.post(
2022-09-26T01:10:19.670843944Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
2022-09-26T01:10:19.670867369Z     result = self._request_wrapper(
2022-09-26T01:10:19.670890184Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 290, in _request_wrapper
2022-09-26T01:10:19.670913795Z     raise NetworkError('Bad Gateway')
2022-09-26T01:10:19.670936369Z telegram.error.NetworkError: Bad Gateway
2022-09-26T01:10:20.745674881Z Error while getting Updates: Bad Gateway
2022-09-26T01:10:20.748856476Z No error handlers are registered, logging exception.
2022-09-26T01:10:20.748969271Z Traceback (most recent call last):
2022-09-26T01:10:20.749006215Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
2022-09-26T01:10:20.749042234Z     if not action_cb():
2022-09-26T01:10:20.749075918Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
2022-09-26T01:10:20.749198936Z     updates = self.bot.get_updates(
2022-09-26T01:10:20.749234491Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 226, in get_updates
2022-09-26T01:10:20.749269509Z     updates = super().get_updates(
2022-09-26T01:10:20.749302712Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
2022-09-26T01:10:20.749337101Z     result = func(*args, **kwargs)
2022-09-26T01:10:20.749370600Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 3057, in get_updates
2022-09-26T01:10:20.749404989Z     self._post(
2022-09-26T01:10:20.749437840Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
2022-09-26T01:10:20.749471692Z     return self.request.post(
2022-09-26T01:10:20.749504377Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
2022-09-26T01:10:20.749538636Z     result = self._request_wrapper(
2022-09-26T01:10:20.749571302Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 290, in _request_wrapper
2022-09-26T01:10:20.749604968Z     raise NetworkError('Bad Gateway')
2022-09-26T01:10:20.749637394Z telegram.error.NetworkError: Bad Gateway
2022-09-26T01:19:32.282577433Z 2022-09-26 01:19:32,277 - addarr - DEBUG - reply is test
2022-09-26T01:19:32.282997521Z 2022-09-26 01:19:32,282 - addarr - DEBUG - User entered a title test
2022-09-27T16:08:38.162590947Z No error handlers are registered, logging exception.
2022-09-27T16:08:38.166863676Z Traceback (most recent call last):
2022-09-27T16:08:38.166920676Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
2022-09-27T16:08:38.166948268Z     handler.handle_update(update, self, check, context)
2022-09-27T16:08:38.166974286Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 627, in handle_update
2022-09-27T16:08:38.167000601Z     new_state = handler.handle_update(update, dispatcher, check_result, context)
2022-09-27T16:08:38.167026322Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
2022-09-27T16:08:38.167053100Z     return self.callback(update, context)
2022-09-27T16:08:38.167078618Z TypeError: 'module' object is not callable
2022-09-27T23:15:11.628123214Z 2022-09-27 23:15:11,626 - addarr - DEBUG - Addarr v0.6 starting up...
2022-09-27T23:15:11.630575998Z 2022-09-27 23:15:11,630 - addarr - DEBUG - Addarr v0.6 starting up...
2022-09-27T23:15:11.722057063Z /usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py:288: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2022-09-27T23:15:11.722148136Z   warnings.warn(
2022-09-27T23:15:11.727272683Z 2022-09-27 23:15:11,726 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.

I believe this is unrelated to the [other issue about user inputs I raised recently](https://github.com/Waterboy1602/Addarr/issues/133).

**Comment by spiveym** [comment]
![image](https://user-images.githubusercontent.com/15334317/192657212-275de80a-3fd4-4075-baa1-7386f71e5d04.png)

Hopefully, that helps to illustrate the issue.

> 2022-09-27T23:30:48.686680394Z No error handlers are registered, logging exception.
2022-09-27T23:30:48.686792115Z Traceback (most recent call last):
2022-09-27T23:30:48.686810929Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
2022-09-27T23:30:48.686828873Z     handler.handle_update(update, self, check, context)
2022-09-27T23:30:48.686845947Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 627, in handle_update
2022-09-27T23:30:48.686863429Z     new_state = handler.handle_update(update, dispatcher, check_result, context)
2022-09-27T23:30:48.686880336Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
2022-09-27T23:30:48.686897262Z     return self.callback(update, context)
2022-09-27T23:30:48.686913613Z   File "/app/src/addarr.py", line 564, in nextOption
2022-09-27T23:30:48.686930094Z     msg = context.bot.send_message(
2022-09-27T23:30:48.686946557Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
2022-09-27T23:30:48.686963464Z     result = func(*args, **kwargs)
2022-09-27T23:30:48.686979742Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 525, in send_message
2022-09-27T23:30:48.686996594Z     return self._message(  # type: ignore[return-value]
2022-09-27T23:30:48.687013279Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 202, in _message
2022-09-27T23:30:48.687030130Z     result = super()._message(
2022-09-27T23:30:48.687046482Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 339, in _message
2022-09-27T23:30:48.687063334Z     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2022-09-27T23:30:48.687079889Z   File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
2022-09-27T23:30:48.687096574Z     return self.request.post(
2022-09-27T23:30:48.687112889Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
2022-09-27T23:30:48.687129944Z     result = self._request_wrapper(
2022-09-27T23:30:48.687146518Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
2022-09-27T23:30:48.687163295Z     message = str(self._parse(resp.data))
2022-09-27T23:30:48.687179703Z   File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 230, in _parse
2022-09-27T23:30:48.687196554Z     raise RetryAfter(retry_after)
2022-09-27T23:30:48.687257720Z telegram.error.RetryAfter: Flood control exceeded. Retry in 26.0 seconds
2022-09-27T23:50:33.428556700Z No error handlers are registered, logging exception.
2022-09-27T23:50:33.428702050Z Traceback (most recent call last):
2022-09-27T23:50:33.428735938Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
2022-09-27T23:50:33.428766142Z     handler.handle_update(update, self, check, context)
2022-09-27T23:50:33.428794660Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 627, in handle_update
2022-09-27T23:50:33.428823326Z     new_state = handler.handle_update(update, dispatcher, check_result, context)
2022-09-27T23:50:33.428850974Z   File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
2022-09-27T23:50:33.428878937Z     return self.callback(update, context)
2022-09-27T23:50:33.428906085Z TypeError: 'module' object is not callable

**Comment by Waterboy1602** [comment]
I can't directly recognize the problem or bug by looking at the logs. Could it be that your service lost internet connection, because I see in the logs `bad gateway`.

I've also never heard about these bugs before. Is there a specific command you've entered before it started not working anymore?

**Comment by matann1991** [comment]
It happened to me also when i tried /delete command.

**Comment by zeljkoperic** [comment]
command /delete does not work for mee too
