### ISSUE TITLE
addarr    | ValueError: Command is not a valid bot command

### ISSUE THREAD

**Issue by billouetaudrey** [Waterboy1602/Addarr#139]
Hey, can start bot using docker, any help please ?

```
Starting addarr ... done
Attaching to addarr
addarr    | Traceback (most recent call last):
addarr    |   File "/app/src/addarr.py", line 832, in <module>
addarr    |     main()
addarr    |   File "/app/src/addarr.py", line 54, in main
addarr    |     auth_handler_command = CommandHandler(config["entrypointAuth"], authentication)
addarr    |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/commandhandler.py", line 164, in __init__
addarr    |     raise ValueError('Command is not a valid bot command')
addarr    | ValueError: Command is not a valid bot command
addarr exited with code 1
```

**Comment by billouetaudrey** [comment]
Fixed, sorry
