### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by figgzs** [Waterboy1602/Addarr#145]
Hello

This my 1st time using telegram bots and python... so take it easy on the noob please :)
After much trial and error i've finnally hit a wall that a ican't pass.
As long as python was complaining about the config.yaml file i was able to see where the problem was, but this case i have no idea...

C:\Addarr\src>python addarr.py
Traceback (most recent call last):
  File "C:\Addarr\src\addarr.py", line 19, in <module>
    import delete as delete
  File "C:\Addarr\src\delete.py", line 11, in <module>
    from addarr import getService, clearUserData, stop
  File "C:\Addarr\src\addarr.py", line 35, in <module>
    application = Application.builder().token(config["telegram"]["token"]).build()
                                              ~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

[config-copy.txt](https://github.com/Waterboy1602/Addarr/files/13443586/config-copy.txt)

what did i did wrong?
thank you in advance for your help.

**Comment by Waterboy1602** [comment]
Does your Telegram token exists out of two parts that are connected with an `:`? It should be 9 numbers followed by an `:` and then a string of characters

**Comment by figgzs** [comment]
my telegram token has 10 numbers : and then a string chars.

**Comment by Waterboy1602** [comment]
I've tried changing the form of the Telegram token in my config.yaml and Addarr starts without problem. So I guess it has nothing to do with the fact that your token exists out of 10 numbers.

I've also looked into your config-file and doesn't see any problems on the first sight. To be honest I've also never experienced your  error message before

**Comment by figgzs** [comment]
hummm ok i'll start from new vm, i'm using windows 11 virtual machine btw.
this one has plex  sonarr/radarr and prowlarr working great, but i'll install e new one clear from all other software and get back to you.

**Comment by figgzs** [comment]
thank you very much :)

**Comment by figgzs** [comment]
Hello 
good news got it to start :)
been adding/removing spaces on the variables in config.yaml and got it to "talk" to me in telegram.
But when i say the type of search (movies/series) e does npt respond.
![image](https://github.com/Waterboy1602/Addarr/assets/105708377/705f0ab2-c1a0-47b1-9cd8-ed57b7726cd3)

and on the console i've got the folling error:

c:\Addarr\src>python addarr.py
c:\Addarr\src\addarr.py:832: RuntimeWarning: coroutine 'startCheck' was never awaited
  if startCheck():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-11-24 05:14:50,426 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.

2023-11-24 05:15:10,239 - addarr.commons - WARNING - Generate of APIQUERY failed: string indices must be integers, not 'str'.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\telegram\ext\_application.py", line 1195, in process_update
    await coroutine
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\telegram\ext\_conversationhandler.py", line 850, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\telegram\ext\_basehandler.py", line 153, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Addarr\src\addarr.py", line 389, in searchSerieMovie
    searchResult = service.search(title)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Addarr\src\sonarr.py", line 23, in search
    req = requests.get(commons.generateApiQuery("sonarr", "series/lookup", parameters))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by bulletproof2k** [comment]
I also noticed that it doesn't add anything to sonarr/radarr returns an error when adding all seasons: ```
Unfortunately, it was not possible to add the series. 
To start a new search, enter - films
```
