### ISSUE TITLE
Error at chosse Quality 

### ISSUE THREAD

**Issue by Antxis77** [Waterboy1602/Addarr#149]
Hi,

I am contacting you because I am getting an error when selecting the quality of the film on Telegram.

I am attaching the written error and some configurations.
The commands /allmovies and /allSeries are working.

Error :

2024-01-16 10:18:30,151 - addarr.radarr - INFO - http://192.168.1.95:7878/api/v3/movie/lookup?apikey=a1614895707843d785b8e9f6e4332bb3&term=la%20tresse
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/plex/.local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1234, in process_update
    await coroutine
  File "/home/plex/.local/lib/python3.10/site-packages/telegram/ext/_conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
  File "/home/plex/.local/lib/python3.10/site-packages/telegram/ext/_basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/opt/Addarr/src/addarr.py", line 684, in selectSeasons
    return await addSerieMovie(update, context)
  File "/opt/Addarr/src/addarr.py", line 817, in addSerieMovie
    service.createTag(str(update.effective_message.chat.id))
  File "/opt/Addarr/src/radarr.py", line 147, in createTag
    "id": max([t["id"] for t in getTags()])+1,
ValueError: max() arg is an empty sequence

Config : 

![Capture d'écran 2024-01-16 112305](https://github.com/Waterboy1602/Addarr/assets/64417162/b5e44c90-af02-44cb-a709-28629364db64)

![Capture d'écran 2024-01-16 112352](https://github.com/Waterboy1602/Addarr/assets/64417162/bd43efe8-861f-4161-a99f-7d0a4562cea3)

![Capture d'écran 2024-01-16 112530](https://github.com/Waterboy1602/Addarr/assets/64417162/580f8c50-4665-4b62-8c4f-504035f94043)

**Comment by Antxis77** [comment]
I fix problem addRequesterIdTag: true to false
