### ISSUE TITLE
IndexError when search for movie title "The Ministry of Ungentlemanly Warfare" [BUG]

### ISSUE THREAD

**Issue by RPWouters** [Waterboy1602/Addarr#151]
I'm encountering an `IndexError` when using a Telegram bot integrated with Radarr to search for movie titles. The issue arises specifically when searching for the movie title "The Ministry of Ungentlemanly Warfare."

**Steps to Reproduce**
1. Start the Telegram bot.
2. Enter the movie title "The Ministry of Ungentlemanly Warfare."
3. The bot attempts to fetch details from Radarr.
4. An `IndexError` occurs.

**Expected Behavior**
The bot should successfully retrieve the movie details from Radarr and display them to the user.

**Current Behavior**
The bot fails to handle the movie search query and crashes, resulting in an `IndexError`. 

**Log Snippet**

2024-01-30 22:19:49,101 - addarr - DEBUG - Removing choice, title, position, paths, and output from context.user_data...
2024-01-30 22:19:57,501 - addarr - DEBUG - reply is The Ministry of Ungentlemanly Warfare
2024-01-30 22:19:57,501 - addarr - DEBUG - User entered a title The Ministry of Ungentlemanly Warfare
2024-01-30 22:19:58,623 - addarr.radarr - INFO - http://192.168.2.22:7878/api/v3/movie/lookup?apikey=xxxxxxxxxxxxxxx&term=The%20Ministry%20of%20Ungentlemanly%20Warfare
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1195, in process_update
    await coroutine
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_conversationhandler.py", line 850, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 153, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/addarr.py", line 400, in searchSerieMovie
    message += f"\n\n*{context.user_data['output'][position]['title']} ({context.user_data['output'][position]['year']})*"
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range

**Comment by Waterboy1602** [comment]
It had to do with the fact that this movie doesn't have a poster in Radarr (and I guess TMDB). My code explicitly checked if it had a couple of values and a poster was one of those. Now I've deleted the need of having a poster. 

As this got fixed with my latest commit, I'll close this issue.
