### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

### ISSUE THREAD

**Issue by bulletproof2k** [Waterboy1602/Addarr#157]
```
D:\Addarr\src>python addarr.py
2024-03-19 17:19:30,119 - addarr - INFO - Начните общаться с Addarr в Telegram. При первом использовании "films" вам будет предложено ввести пароль.
D:\Addarr\src\sabnzbd.py:61: RuntimeWarning: coroutine 'Message.reply_text' was never awaited
  update.message.reply_text(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-03-19 17:20:56,162 - addarr.commons - WARNING - No ip or port defined.
2024-03-19 17:20:56,162 - addarr.commons - WARNING - Generate of APIQUERY failed: unsupported operand type(s) for +: 'NoneType' and 'str'.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1264, in process_update
    await coroutine
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handlers\conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Addarr\src\addarr.py", line 359, in choiceSerieMovie
    return await searchSerieMovie(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Addarr\src\addarr.py", line 401, in searchSerieMovie
    searchResult = service.search(title)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Addarr\src\sonarr.py", line 23, in search
    req = requests.get(commons.generateApiQuery("sonarr", "series/lookup", parameters))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

An error occurs when requesting episodes, movies, as well as when requesting download clients.

**Comment by bulletproof2k** [comment]
radarr/sonarr I figured it out on my own, it remains to understand about errors for download clients. 👍
