### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by flags8192** [Waterboy1602/Addarr#158]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1234, in process_update
    await coroutine
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/addarr.py", line 594, in pathSerieMovie
    return await qualityProfileSerieMovie(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/addarr.py", line 646, in qualityProfileSerieMovie
    return await selectSeasons(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/addarr.py", line 684, in selectSeasons
    return await addSerieMovie(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/addarr.py", line 817, in addSerieMovie
    service.createTag(str(update.effective_message.chat.id))
  File "/app/src/radarr.py", line 147, in createTag
    "id": max([t["id"] for t in getTags()])+1,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

**Comment by Waterboy1602** [comment]
It looks like you're not on the latest version of Addarr. This is the same issue as #155 and got fixed with the latest commit [#831767c](https://github.com/Waterboy1602/Addarr/commit/831767c8fd15df44b24dd8e438c4bcd9d2947dc3)
