### ISSUE TITLE
Port issue 

### ISSUE THREAD

**Issue by tulkarxxx** [Waterboy1602/Addarr#27]
Hi , my server is running with dockers and letsencrypt, 
Every container app have its own subdomain, for example :
https://sonarr.mydomain.com
Checking the log I see the error is raised because the url string generated by addarr when requesting api info
Sample;
https://sonarr.mydomain.com:None/api/series/lookup?apikey=XXXXXXXXXXXXXXXXXXXXXXXXXXXX&term=Charmed
As no port is used that is affecting generated url , adding string ":None" inside url, if I remove manually that url works, for  example
https://sonarr.mydomain.com/api/series/lookup?apikey=XXXXXXXXXXXXXXXXXXXXXXXXXXXX&term=Charmed works

**Comment by tulkarxxx** [comment]
This is my config
#Sonarr Configuration
sonarr:
  server:
    addr: sonarr.mydomin,com
    port : 443
    ssl: false #default false
  auth:
    apikey: XXXXXXXXXXXXXXXXXXXXXXXXXX
    username: myuser
    password: mypass
  search: true
  seasonFolder: true
  qualityProfileId: 1

And this is the error received:
2020-07-10 10:25:51,862 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/app/addarr.py", line 337, in searchSerieMovie
    context.user_data["output"] = service.giveTitles(service.search(title))
  File "/app/sonarr.py", line 26, in search
    parsed_json = json.loads(req.text)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tulkarxxx** [comment]
CLosed, my configuration issues
