### ISSUE TITLE
Not able to add movies or series

### ISSUE THREAD

**Issue by jamiehlake** [Waterboy1602/Addarr#43]
I'm new to all this so please bear with me.

I have set up the bot but after selecting Movie or Series nothing happens. The output on CMD is the following: 

C:\Users\Administrator>A:\Addarr-master\addarr.py
2021-01-30 13:37:00,474 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.
2021-01-30 13:37:17,740 - addarr.commons - WARNING - Generate of APIQUERY failed: 'auth'.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "A:\Addarr-master\addarr.py", line 366, in searchSerieMovie
    searchResult = service.search(title)
  File "A:\Addarr-master\sonarr.py", line 25, in search
    req = requests.get(commons.generateApiQuery("sonarr", "series/lookup", parameters))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

And my configuration file is:

#Restrict some commands (Transmission) to only admins 
enableAdmin: true

#Sonarr Configuration
sonarr:
  server: 
  addr: http://127.0.0.1
  port: 8989 # Default is 8989
  path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
  ssl: false #default false
auth:
  apikey: (Added the API Key found in sonarr settings)
  username: 
  password: 
  search: true
  seasonFolder: true
  qualityProfileId: 1

#Radarr Configuration
radarr:
  server: 
  addr: http://127.0.0.1
  port : 7878 # Default is 7878
  path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
  ssl: false #default false
auth:
  apikey: (Added the API Key found in radarr settings)
  username: 
  password: 
  search: true
  qualityProfileId: 1

#Telegram Configuration
telegram:
  token: (Telegram bot token)
  password: 

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:
  authentication: true #is transmission protected with a password?
  username: 
  password:

#Language
language: en

#Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

#Logging
logToConsole: true
debugLogging: true

The log file just has the "Generate of APIQUERY failed: 'auth'." warning 
Let me know if there is any more info I could provide.

**Comment by tedvdb** [comment]
Is your `config.yaml` file properly indented? That can cause this issue. The spaces in front of the values are important for correct parsing of your config file.

If so, could you post your config again, but then between as this? This keeps the identation.
> \```
> Your config
> \```

**Comment by Waterboy1602** [comment]
I'll close this issue, as there hasn't been a response in more than a month.
