### ISSUE TITLE
i'm getting error when installing on windows 10

### ISSUE THREAD

**Issue by idandd** [Waterboy1602/Addarr#69]
i am getting these errors when installing 
hope someone can help?

C:\Addarr\Addarr>python addarr.py
Traceback (most recent call last):
  File "C:\Addarr\Addarr\addarr.py", line 11, in <module>
    from commons import checkId, authentication, format_bytes, format_long_list_message
  File "C:\Addarr\Addarr\commons.py", line 5, in <module>
    from config import config
  File "C:\Addarr\Addarr\config.py", line 5, in <module>
    config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Addarr\\Addarr\\config.yaml'

**Comment by Waterboy1602** [comment]
It looks like you haven't changed the name of `config_example.yaml` to `config.yaml` yet

**Comment by idandd** [comment]
yep. you were right ! thanks. 
but now i get this error:

Traceback (most recent call last):
  File "C:\Addarr\Addarr\addarr.py", line 27, in <module>
    updater = Updater(config["telegram"]["token"], use_context=True)
  File "C:\Users\Idan\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\updater.py", line 237, in __init__
    raise ValueError('`token` or `bot` must be passed')
ValueError: `token` or `bot` must be passed

What should i do?
