### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/app/config.yaml'

### ISSUE THREAD

**Issue by ahmaddarzani** [Waterboy1602/Addarr#95]
IsADirectoryError: [Errno 21] Is a directory: '/app/config.yaml'

**Comment by Waterboy1602** [comment]
What are you trying to say with this issue?

**Comment by ahmaddarzani** [comment]
Docker Container Installation then I start it then I get Errno21 and I don't know where is the problem
thank you

**Comment by ahmaddarzani** [comment]
I have that in the logs
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
IsADirectoryError: [Errno 21] Is a directory: '/app/config.yaml'
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
IsADirectoryError: [Errno 21] Is a directory: '/app/config.yaml'

**Comment by Waterboy1602** [comment]
Are you sure that you've made the `config.yaml` file with your configuration settings? It looks like that is what the error is saying.

**Comment by ahmaddarzani** [comment]
Yes

sonarr:
  server: 199.111.666
    addr: 
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: 269************5ae50b6
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1
  languageProfileId: 1
  excludedRootFolders: # If set must start and finish with / Eg: /mnt/Media/
    - # First excluded folder, add others with a "-" on a new line (same indentation)

#Radarr Configuration
radarr:
  server: 199.111.666
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: 9cd50************75e0841
    username:
    password: 
  search: true
  qualityProfileId: 1
  minimumAvailability: announced
  excludedRootFolders: # If set, must start and finish with / Eg: /mnt/Media/
    - # First excluded folder, add others with a "-" on a new line (same indentation)

#Telegram Configuration
telegram: 5*******51:AAFF4************
  token:
  password:

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host: # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username: 
  password:

sabnzbd:
  enable: true
  onlyAdmin: true
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password:

# Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands (Transmission) to only admins 
enableAdmin: true

##Logging
logToConsole: true
debugLogging: false

**Comment by Waterboy1602** [comment]
If I Google the error, it says that the problem is that `config.yaml` is a folder instead of a file. So please double check if the file is in the correct place and even exists.

There are also some problems in your `config.yaml` file. The IP-adress should be at `addr`, not at `server`. And be sure that the correct indentation is kept.

**Comment by ahmaddarzani** [comment]
I did as you told me but I got it
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
Traceback (most recent call last):
File "/app/addarr.py", line 12, in <module>
from commons import checkAdmin, checkId, authentication, format_bytes, format_long_list_message, getAuthChats
File "/app/commons.py", line 5, in <module>
from config import config
File "/app/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "/app/config.yaml", line 22, column 10
