### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mipiaceanutella** [Waterboy1602/Addarr#98]
2022-01-13 11:19:10,545 - addarr.commons - WARNING - Generate of APIQUERY failed: 'NoneType' object is not subscriptable.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "addarr.py", line 306, in searchSerieMovie
    searchResult = service.search(title)
  File "/root/addarr/Addarr/sonarr.py", line 23, in search
    req = requests.get(commons.generateApiQuery("sonarr", "series/lookup", parameters))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by Mipiaceanutella** [comment]
[here](https://pastebin.com/raw/rB0MWxDy)
